---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      version: 1.19.3
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
    disableWait: false
  interval: 1m0s
  releaseName: istio-base
  targetNamespace: istio-system
  values:
    global.istioNamespace: istio-system
