---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gateway
      version: 1.19.2
      interval: 5m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: istio-base
      namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: false
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: istio-gateway
  targetNamespace: istio-system
