---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: istiod
      version: 1.19.3
      interval: 5m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
    disableWait: false
  dependsOn:
    - name: istio-base
      namespace: flux-system
  interval: 1m0s
  releaseName: istiod
  targetNamespace: istio-system
  values:
    global.istioNamespace: istio-system
